<?php
/**
 * RSS Grabber Config (generated by install)
 *
 * This file is generated by the install script.
 * If it does not exist, the application redirects to ./install/
 */
if (realpath($_SERVER["SCRIPT_FILENAME"] ?? '') === __FILE__) {
    header('Location: ../index.php');
    die();
}
/** @var string */
$script_version = '';
/** @var string */
$db_host = '';
/** @var string */
$db_datenbank = '';
/** @var string */
$db_user = '';
/** @var string */
$db_passwort = '';
/** @var string */
$anzahl_grabber_pro_lauf = '';
/** @var int */
$anz_anzeige = 25;
/** @var int */
$max_laege_description = 250;
/** @var string */
$iso_to_utf = '1';
